// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Configurations;

namespace webapi.Migrations
{
    [DbContext(typeof(EntityContext))]
    partial class EntityContextConfigModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("webapi.Modules.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Activo"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Deactivo"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cancelado"
                        },
                        new
                        {
                            Id = 4,
                            Description = "In Progress"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Paused"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Completed"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Asigned"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Pending"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
